# Generated by Django 5.1.7 on 2025-03-16 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0002_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 16, 15, 6, 0, 510111, tzinfo=datetime.timezone.utc)),
        ),
    ]
