# Generated by Django 5.1.7 on 2025-03-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0004_category_remove_article_pub_date_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
