# Generated by Django 5.1.7 on 2025-03-25 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0011_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
