# Generated by Django 5.1.7 on 2025-03-31 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'حساب کاربری', 'verbose_name_plural': 'حساب های کاربری'},
        ),
    ]
